### ISSUE TITLE
What does is take to have IFTTT in Dutch too?

### ISSUE THREAD

**Issue by Coldrush** [maykar/plex_assistant#104]
Hello!

I just came across this project. Pretty awesome work!

I also noticed that there isn't a Dutch version of IFTTT yet. Other than the translation, are there any technical reasons for IFTTT not being available in Dutch? 

If we only need to take care of the translation, what work are we looking at?

Looking forward to your reply!

**Comment by maykar** [comment]
There is nothing we can do to add languages to IFTTT. You would need either IFTTT or Google to update the service to support more languages.

**Comment by Coldrush** [comment]
Ok got you!
