### ISSUE TITLE
Not finding season / episode when it exists

### ISSUE THREAD

**Issue by 1ntroduc3** [maykar/plex_assistant#108]
Play "The Blacklist" is playing episode 1 always, I think because of multiple profiles? How can I force another profile to be picked?

**Comment by maykar** [comment]
Is episode one listed as unwatched? Plex Assistant checks for the first item tagged as unwatched, unless a specific season and/or episode is requested.

**Comment by maykar** [comment]
No, unfortunately, with managed-users, but not playing via season and episode is an issue. Can you enable debug logs to see if we can get any more info as to what's going on there?

**Comment by 1ntroduc3** [comment]
I can't seem to find the correct logs. what's the correct configuration.yaml config for the plexassistant logs?

**Comment by 1ntroduc3** [comment]
`Error executing service: <ServiceCall plex_assistant.command (c:1e93f56dc9a9775881a05afe007a001e): command=play the Blacklist season 8 episode 3>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1504, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 132, in handle_input
    media, offset = filter_media(pa, command, media, library)
  File "/config/custom_components/plex_assistant/helpers.py", line 203, in filter_media
    media = media.episode(season=int(command["season"] or 1), episode=int(command["episode"]))
AttributeError: 'list' object has no attribute 'episode'`

**Comment by 1ntroduc3** [comment]
If i ask plex to play a movie, or the latest episode of the blacklist.. it works. Just "the blacklist, won't work..  If i ask to play "the blacklist" it says "blacklist not found"  on my tv.

**Comment by 1ntroduc3** [comment]
Do you have any update on this maybe?

**Comment by maykar** [comment]
I've been trying to recreate the issue without luck so far. I've been pretty unavailable recently, real life has really piled it on as of late. So, I haven't been able to dive too deep into this quite yet. If you wouldn't mind attempting something it would help track this down a bit. In the file `helpers.py` on line 202 can you add `_LOGGER.warning(f"Media Check: {media}")` right above so it would look like this:

```
    if isinstance(media, list) and len(media) == 1:
        media = media[0]

    _LOGGER.warning(f"Media Check: {media}")

    if command["episode"]:
        media = media.episode(season=int(command["season"] or 1), episode=int(command["episode"]))
    elif command["season"]:
        media = media.season(season=int(command["season"]))
```

And let me know what shows up in your logs.
