### ISSUE TITLE
Since 0.0.6 update I get an error 

### ISSUE THREAD

**Issue by marcokreeft87** [maykar/plex_assistant#11]
Component error: plex_assistant - Requirements for plex_assistant not found: ['python-Levenshtein==0.12.0'].

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.4.59+
python_version | 3.7.7
timezone | Europe/Amsterdam
version | 0.107.7
virtualenv | false

**Comment by maykar** [comment]
Python-Levenshtein was removed as a requirement in 0.0.4. Try reinstalling. If you're installing manually be sure to install all the files, especially manifest.json.

If you're still having issues try deleting the `__pycache__` folder inside the components folder.
