### ISSUE TITLE
Play as specified home user

### ISSUE THREAD

**Issue by Shayne55434** [maykar/plex_assistant#119]
Not sure if this is possible or not, but it would be really cool to specify which user to play as. Currently, it plays as the server owner/admin. However, I have a separate home user account I'd like to play media as. Hope this is possible and can be added!

**Comment by maykar** [comment]
This is an often suggested feature, but there is no current practical way to implement something like this. IFTTT doesn't pass along user, device, etc. information and to do this with dialogflow would require quite a bit of work and may not even be possible as well for a few reasons, not least of which is I don't believe that you can make an Assistant plugin with a variable webhook address.

**Comment by Shayne55434** [comment]
That's fair. However, couldn't you specify a user as default within HA, rather than passing it through IFTTT/GA?

**Comment by maykar** [comment]
This project uses HA's built in Plex integration services for starting playback, currently there is no feature for "Play as user". Might be a good feature request for HA core.
