### ISSUE TITLE
Error with 0.8 and 0.107.7

### ISSUE THREAD

**Issue by jmacul2** [maykar/plex_assistant#12]
```
Logger: homeassistant.setup
Source: custom_components/plex_assistant/helpers.py:26
First occurred: 4:38:20 PM (1 occurrences)
Last logged: 4:38:20 PM

Error during setup of component plex_assistant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 75, in setup
    PA.lib = get_libraries(PA.plex)
  File "/config/custom_components/plex_assistant/helpers.py", line 26, in get_libraries
    shows.sort(key=lambda x: x.updatedAt)
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

I tried using master and got the same bug....FYI.

**Comment by maykar** [comment]
Interesting, seems like either you have a show with no updatedAt attribute or the connection to plex failed. Looking into it.

**Comment by maykar** [comment]
Updated master that adds a fallback in case a show doesn't have an updatedAt attribute. Falls back to addedAt.

Let me know if that solves it for you.

**Comment by OppyLock** [comment]
I had the same issue, and that solved it for me.  No more errors at least.  Now if only I could get Plex to play anything via HA that would be great. ;)

**Comment by jmacul2** [comment]
That fixed it thanks.

I found a few other interesting things FWIW.

1.  It appears none of my cast devices are recognized unless I use aliases.  I have to alias 'Bedroom TV' by its same name for it to work.
2.  Using DialogFlow, any Plex remote server takes a long time to respond whereby Google Assistant returns and says it cant communicate with plex, but then a minute later it works.  Not sure if this can be addressed or not.

Thanks for all your work!  I'll probably fork this and start adding merge requests.  This integration shows lots of promise!  :)

**Comment by maykar** [comment]
Haven't been able to track down the issue with aliases yet, someone else was having a similar issue. It's all working great on my setup and I've been trying to recreate the issue, but so far no luck.

DialogFlow is way more finicky than the IFTTT option. They are both doing the same thing, just passing the command to HA to be processed by the component, but there is for sure some strangeness associated with how DialogFlow handles it.

**Comment by maykar** [comment]
Released the fix for this one, going to close the issue.

@jmacul2 feel free to message me over on the HA forums if you have any questions.

@OppyLock I'm not sure what you mean with your comment, is it that this component isn't working for you or are you trying to do something else?

**Comment by OppyLock** [comment]
The component isn't working for me, in that I can't test it.  It throws no errors now.
However, i can't get Plex to play anything on anything when initiated by HA with the play_media service.  It throws a bunch of errors doing that and also when requested via plex assistant, so its not a plex assistant issue.
The Plex integration seems to work and updates the activities of the media players, I jcan start/stop/pause/skip, etc, but i can't initiate anything.  It throws TCP errors saying it can't open a websocket ... so I'll work through that ;)
