### ISSUE TITLE
Using aliases in newest version

### ISSUE THREAD

**Issue by exetico** [maykar/plex_assistant#122]
Hi,

I've updated to the new version, and followed the update-guide, but there's no option for "aliases" anymore.

Are it removed 100%? The "Friendly name" only gives me one alternativ pr. device, and that's a bit too little for me, in some cases.

Are there a work-around for this, or can it be defined as a bug?

**Comment by maykar** [comment]
If you want to use multiple names for a single device use the [keyword replacement](https://github.com/maykar/plex_assistant#keyword-replacements) feature.

Example:

You have a device with the friendly name of "My Device", but want to also be able to call it "Downstairs" and "Living Room". Your keyword replacement config would look like this:

`"downstairs":"my device", "living room":"my device"`

Now you can say "Downstairs", "Living Room", and "My Device" all for the same device.
