### ISSUE TITLE
Plex does not report playing status when playing via Plex Assistant

### ISSUE THREAD

**Issue by teflocarbon** [maykar/plex_assistant#128]
Hi there,

I'm having some very strange issues with Plex Assistant updating Plex on it's status, specifically when using HA's Plex integration to poll for states.

For whatever reason, when using Plex Assistant to play content, it'll play fine on the device however, Plex's HA integration will not update the state. It will simply show as 'idle'. Even stranger, Plex will not show the content playing in the server's dashboard, it will simply say that nothing is playing, despite there very clearly being something playing. It says this on both the web client and Plex Dash application.

When you play the content via the normal method of through the UI, it will always show up and update the state. The content will also come up if you are casting via a phone, I've only tested on my iPhone via the Plex app though.

Plex Client: Android TV (8.18.0.25332)
Plex Client: iOS (7.17)
Plex Server: (Public 1.22.3.4523)
HA:  OS-VM (core-2021.5.5)
Plex Assistant: 1.1.6
Trigger Method: IFTTT
Installation Method: HACS

**Comment by LeTailleCrayon** [comment]
Hello,
Same problem for me. HA detects when I pause the movie but when I play it again it doesn't detect anything...
I use Home Assistant Docker.
Thanks

**Comment by maykar** [comment]
** Disclaimer: Bear with me as I have very little time to work on my projects at the moment as I am currently going through a divorce, finding a new place to live, moving, and still keeping my sanity.

If you use developer tools service `media_player.play_media` to cast plex media to the same device, does it exhibit the same symptoms?
