### ISSUE TITLE
Command to play "next track" is ignored?

### ISSUE THREAD

**Issue by pjft** [maykar/plex_assistant#130]
No errors.
Installed manually.
Everything works without issue.

However, I can't seem to ask Plex to play the next audio track. I can ask it to pause, stop and resume. But if I ask "next", "next track", "skip track", the command seems to be ignored.

On my Google Home app, the "next" icon in the controls is also greyed out, so it's probable that it has something to do with it. That being said, other songs will play just fine after the current one.

Anything I can share here?

**Comment by maykar** [comment]
** Disclaimer: Bear with me as I have very little time to work on my projects at the moment as I am currently going through a divorce, finding a new place to live, moving, and still keeping my sanity.

Please provide as much of the info requested in the bot's reply above.

**Comment by pjft** [comment]
First of all, so sorry to hear about that. Do take care of yourself, first and foremost.

I suppose, for anyone who runs into this, it actually works, the difference to other providers is that you can't really just say "Next track". You need to say "<plex command> Next track <on optional speaker, if not on default>".

When I say "Tell Plex to Next Track on Office Speaker" (if I'm playing on Office Speaker) then it finally works.

Apologies.
