### ISSUE TITLE
Multiple Plex servers configured error

### ISSUE THREAD

**Issue by CubeComming** [maykar/plex_assistant#131]
Soo I recently added a second Plex Server, and now it stopped working.

I have reinstalled the plex assistant addon and changed the Server, to the one I want.

Log:
``` 
Error executing service: <ServiceCall media_player.play_media (c:9f462354509cada88023c3ad762e9d32): entity_id= ['media_player.chromecast'], extra=, media_type=video, media_id=plex://{"playqueue_id": 35, "type": "audio"}>
homeassistant.exceptions.HomeAssistantError: Multiple Plex servers configured, choose with 'plex_server' key: ['Admin-Server',  'Music-Server']
```

Installed with HACS
Triggered with Node Red
No advanced options

So I want him to play music from Music-Server but as you can see he doesn't seem to push the variable "plex_server":"Music-Server"....

**Comment by maykar** [comment]
Yup, I see the issue. Expect a fix soonish.

**Comment by maykar** [comment]
Should be good in latest release, let me know if you're still having issues.

**Comment by CubeComming** [comment]
Can confirm works now
Thank you
