### ISSUE TITLE
Play a random episode of a tv shows

### ISSUE THREAD

**Issue by zjuanma** [maykar/plex_assistant#14]
Can you add play a random episode of a tv show?

**Comment by maykar** [comment]
Pushed a minor release before this feature, still need to finish up some features with this one for next release.

**Comment by maykar** [comment]
Added in 1.0.0. Please check out the [update guide](https://github.com/maykar/plex_assistant/blob/master/ver_one_update.md)

**Comment by RyanEwen** [comment]
I'm not sure if it's this library or the Plex integration or perhaps Plex itself, but I'm finding the random is not very random.

I requested a random episode of Futurama 10+ times and usually get the same 3-4 episodes out of all 124. And they're all from season 2.

It seems like every night we ask this, we end up watching the same episodes.

Cheers

**Comment by maykar** [comment]
This actually uses Plex's own shuffle feature. I at one time had Plex Assistant do the shuffling, but that resulted it longer delays and more processing than was needed. I haven't noticed it repeating as you have, but I'll look into it more and if the trade off makes sense I may go back to using my own random implementation.

**Comment by RyanEwen** [comment]
This makes sense and I should have expected it, since using Shuffle right from the Plex app is often pretty repetitive. 

I came to realize that the show we shuffle might as well just be played in order. Feels just as random, haha
