### ISSUE TITLE
IFTTT timed out waiting for response

### ISSUE THREAD

**Issue by tom-dell** [maykar/plex_assistant#158]
Hi, I'm using Plex-Assistant with IFTTT, however whenever I ask Google Assistant to play something, I get the following error from IFTTT; Timed out waiting for response from http://192.168.0.3:8123/api/webhook/61c21e17056xxxx

Do I need to forward the port? Or put it behind my nginx installation? I feel like I might need to, as how is IFTTT going to reach a internal IP.

**Comment by maykar** [comment]
Yes, both Google and IFTTT require remote access to your home assistant instance
