### ISSUE TITLE
Accounts option

### ISSUE THREAD

**Issue by berthavekes2** [maykar/plex_assistant#17]
Is there an option to use multiple plexaccounts?
So that my family members don't watch on my account.

**Comment by maykar** [comment]
Unfortunately, I don't see a good way to implement this without it causing more problems than it's worth.

This would require having to set up multiple plex_assistant configurations each with it's own user's api key and then each person would have to use their own unique phrase, but there would be nothing stopping them from using the other phrases and connecting to the wrong account.

I'll keep this in mind in case I can think up a better solution, but closing this for now.
