### ISSUE TITLE
"pychromecast==4.1.1" breaks Chromecast devices in HA 0.109+

### ISSUE THREAD

**Issue by guice** [maykar/plex_assistant#18]
See: https://github.com/home-assistant/core/issues/34620
And: https://github.com/home-assistant/core/issues/34968

Version-locking of pychromecast is conflicting with Cast updates in HA 0.109+.

**Comment by guice** [comment]
@maykar 

Your recent update didn't resolve the issue. I still had to remove the pychromecast pinning. This time I changed it to `pychromecast>=4.1.1` and it worked.

**Comment by goncalvespedro** [comment]
Hi @guice please can you let me know how you removed the pychromecast pinning as i have the same issue :)
