### ISSUE TITLE
pychromecast conflict? issue

### ISSUE THREAD

**Issue by megahz** [maykar/plex_assistant#21]
Hi, as soon as i installed the plex assistant plugin, the HA stopped discovering casting devices and also shows this error:

`2020-05-19 11:11:40 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform cast.media_player: Platform not found (No module named 'pychromecast.quick_play').
`
once i uninstalled plex_assistant, HA is able to discover chromecast devices again.

it seems that there's a conflict somewhere?

**Comment by maykar** [comment]
Is this still an issue with the latest release?

**Comment by megahz** [comment]
> Is this still an issue with the latest release?

i have reinstalled it now and i think it's ok.
