### ISSUE TITLE
ADD SUPPORT FOR -- Vizio SmartCast TVs -- are Google Cast Enabled but not showing up as supported.

### ISSUE THREAD

**Issue by pgsylvestre** [maykar/plex_assistant#26]
Vizio SmartCast TVs are Google Cast Enabled but not showing up as supported by Plex-assistant.  Each device has a logical name/ id  with which the 'Cast' API can be invoked. 

Consider adding support for the devices in plex-assistant.

**Comment by maykar** [comment]
If the device isn't discovered by my component it's not discovered by pychromecast. I didn't write pychromecast and I don't have a smartcast tv, so there is little I can do to add support. This feature request would be better served on [pychromecast's GitHub](https://github.com/home-assistant-libs/pychromecast).
