### ISSUE TITLE
need to rename services.json to services.yaml

### ISSUE THREAD

**Issue by pgsylvestre** [maykar/plex_assistant#3]
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_assistant/__init__.py", line 76, in handle_input
    call.data.get("command").lower(),
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by maykar** [comment]
This would mean that the service recieved no command. I should add an error that makes this more clear, but the bigger issue is why was there no command sent. When does this happen? Are you using this with IFTTT or just as a service?

**Comment by pgsylvestre** [comment]
I am using the service from developer tools within HA. .

**Comment by pgsylvestre** [comment]
![call](https://user-images.githubusercontent.com/61101978/75159962-35e73380-56e7-11ea-8a11-ca5a20e9d213.png)

**Comment by maykar** [comment]
Did you install manually or with HACS, cause you seem to be missing the file `services.json` that provides you with an example of use.

![image](https://user-images.githubusercontent.com/25127328/75160108-7cd52900-56e7-11ea-8190-22341aee4090.png)

**Comment by pgsylvestre** [comment]
HACS

**Comment by maykar** [comment]
Make sure the file `/custom_components/plex_assistant/services.json` exists. Either way, the image above shows the correct way to call the service.

**Comment by pgsylvestre** [comment]
'services.json' is present in the directory.  Still no help description. Installed from 0.0.3. via HACS

**Comment by maykar** [comment]
Will be fixed in next release, alternatively you can use the "master" branch for now.

**Comment by maykar** [comment]
Fixed in 0.0.4
