### ISSUE TITLE
generator raised StopIteration

### ISSUE THREAD

**Issue by nickjedl** [maykar/plex_assistant#32]
Hello

I'm trying to get this great addon to work but it's throwing errors which I don't understand.

So when trying to trigger from IFTTT I get these errors in de logs:
https://pastebin.com/f2USVQZF and https://pastebin.com/UTQg9tLW

And when trying to trigger from the services menu in Developer Options, I get this one:
https://pastebin.com/Cb8ybAed

Home Assistant 0.111.4 running in Docker on unRAID

**Comment by maykar** [comment]
Please try the latest release (0.2.1) and let me know if it solves it for you.

**Comment by nickjedl** [comment]
Hi, when I call the service in HA my Chromecast starts loading the episode and it looks like it starts to play, but the screen just goes to that 'Plex' grey after it shows the progress bar for a second.
Calling from IFTTT still gives the same error.
I've also decided I won't be using the plugin anymore, I managed to fix the media player I normally use so it's not necessary for me anymore.

**Comment by maykar** [comment]
Sounds like this one is fixed. If anyone else comes across this and has the grey screen issue, this is what the [cast delay](https://github.com/maykar/plex_assistant#cast-delay) option is for.
