### ISSUE TITLE
Flow Documentation For Node Red

### ISSUE THREAD

**Issue by 1h8fulkat** [maykar/plex_assistant#34]
For users running Node Red automations, they can use the following flow instead of the automation YAML, thought you might want to include in your documentation.

![image](https://user-images.githubusercontent.com/11942449/88691363-c547a700-d0ca-11ea-9eb2-e665c96d9d25.png)

`
[{"id":"68283b1e.000664","type":"server-events","z":"9208b996.c075c8","name":"IFTTT WebHook Received","server":"880f9a.58981068","event_type":"ifttt_webhook_received","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"x":1030,"y":460,"wires":[["30b25db9.8a44b2"]]},{"id":"84c76b7a.fdd458","type":"comment","z":"9208b996.c075c8","name":"IFTTT Plex_Assistant WebHook","info":"","x":1050,"y":420,"wires":[]},{"id":"30b25db9.8a44b2","type":"switch","z":"9208b996.c075c8","name":"Plex Assistant","property":"payload.event.service","propertyType":"msg","rules":[{"t":"eq","v":"plex_assistant.command","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":1280,"y":460,"wires":[["b743ac06.b63e3"]]},{"id":"b743ac06.b63e3","type":"api-call-service","z":"9208b996.c075c8","name":"Call Plex Assistant","server":"880f9a.58981068","version":1,"debugenabled":false,"service_domain":"plex_assistant","service":"command","entityId":"","data":"{\t   \"command\": $.payload.event.command\t}","dataType":"jsonata","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":1510,"y":460,"wires":[[]]},{"id":"880f9a.58981068","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
`

**Comment by maykar** [comment]
[HA is required for this project.](https://github.com/maykar/plex_assistant/issues/37)

**Comment by maykar** [comment]
Going to close this as an issue, but post a link to it as an alternative to the automation in the readme.
