### ISSUE TITLE
Playing TV Show only plays one Episode

### ISSUE THREAD

**Issue by demonspork** [maykar/plex_assistant#36]
When I ask it to play a TV Show, it only plays a single episode of the show. Is it possible to modify this behavior so that it plays the show starting at that episode and continuing? Maybe even make it a setting.

If I start the playback from the mobile app, it always continues to the next episode, which is what I am wanting to replicate with the voice controls.

**Comment by kylezimmerman** [comment]
I started looking into this, but found that `plexapi` doesn't support this very well currently, it would have to be done manually.

Submitted an upstream PR to plexapi that should make this much easier to add here https://github.com/pkkid/python-plexapi/pull/561

After that's merged, we should be able to simply change:

```py
plex_c.playMedia(media)
```

to

```py
play_queue = PlayQueue.create(PA.server, media, continuous=1)
plex_c.playMedia(play_queue)
```

**Comment by maykar** [comment]
I'm not sure if that would be nessisary. I'm currently working on it and am instead filtering the episodes by unwatched, by season, etc and adding the returned array into a playlist and then playing that playlist. So in the helper function `video_selection` twards the end (this is a WIP):

```
    if media.type == "show" or media.type == "season":
        unplayed = list(filter(lambda x: not x.isWatched, media.episodes()))
        if len(unplayed) > 0:
            return Playlist.create(PA.server, "PlexAssistant", unplayed)
        return media.episodes()[0]
```

**Comment by maykar** [comment]
I'm not sure if that would be nessisary. I'm currently working on it and am instead filtering the episodes by unwatched, by season, etc and adding the returned array into a playlist and then playing that playlist. So in the helpers.py function `video_selection` at the very end (this is a mostly untested WIP as my kid is busy watching cartoons):

```py
    if media.type == "show" or media.type == "season":
        unplayed = list(filter(lambda x: not x.isWatched, media.episodes()))
        if len(unplayed) > 1:
            return Playlist.create(PA.server, "PlexAssistant", unplayed)
        return media.episodes()[0]
```

Could even do this with onDeck and anything else that could return an array of items

**Comment by kylezimmerman** [comment]
Yeah, it's certainly doable that way (that's what I meant when I said it could be done manually).

I figured since the Plex server already has a `continuous` parameter, it might be best to just let Plex do it's thing. Sniffing the network traffic, that's how the official Plex clients handle it, and it would mean plex_assistant would have the same behavior as other clients.

`PlayQueue` is also a temporary thing, where as `Playlist` creates a new permanent playlist entry in Plex. When I was trying to use `Playlist` I ended up with dozens of playlists with the same name littering my Plex library... 🙁

**Comment by maykar** [comment]
Yeah, I'm thinking that deleting the playlist on each create would be a good idea. That way only one would exist at a time. PlayQueue is an okay solution, but doesn't seem to accept arrays so I would need to loop over each item and add to the queue.

I think your solution would be great and once it's pulled will gladly impliment it, but I also want to avoid using a different version of PlexAPI than what is installed in HA. So it would take time to be pulled into PlexAPI and then even longer before it's added to HA.

**Comment by kylezimmerman** [comment]
That's totally fair, I'm not very well-versed on how quickly all the dependencies get updated.

I'm curious when arrays would be needed? `PlayQueue` will accept a movie, show, season, or an episode and work as you'd expect. `onDeck` is already a playlist that can just be played, so I don't think you'd have to wrap it in another Playlist/PlayQueue.

I also haven't tried it out yet, but what happens if multiple people are using plex at the same time, would the most recent person's request override the playlist and impact others?

At any rate, thanks for working on this, really enjoying finally being able to use Google Assistant to play plex! This issue is the top one I was having issues with, so I thought I'd see what I could do to help 😃.

**Comment by maykar** [comment]
I'm very appreciative of the help, I don't get much time to work on these projects and Custom Header takes up most of the time I get to work on this stuff.

When creating a playlist with PlexAPI I can just feed it a list of episodes which is easy enough to create with a filter. It doesn't seem that this is available for PlayQueue though, so it would require an extra step of iteration over each item in the list and adding it to the playqueue. While this isn't a huge deal, it does add to the time between request and playing.

Good to know about onDeck, need to make sure that I'm allowing that to be returned as a playlist. I think in some cases I'm only returning a single item.

**Comment by maykar** [comment]
As far as multiple people, that's a complication that I haven't really taken on quite yet and in that case it PlayQueue might be a better way to go about it. Really, your PR is the ultimate solution to this so hopefully it won't take long for that to be implimented.

**Comment by maykar** [comment]
Unfortunately, it seems PlayQueue only accepts single media items or playlists which just brings us back to our original issue.

**Comment by kylezimmerman** [comment]
Ah sorry, when I said 

> PlayQueue will accept a movie, show, season, or an episode and work as you'd expect.

I meant after my PR for `continuous=1` support is merged. As of now this won't work unfortunately.

Even still, it would only accept a single item (which can be a movie, show, season, episode, or playlist), and it will build the rest of the Queue from that item, so it doesn't need to take an array at all.

There are a lot of other functions that the actual Plex API supports around PlayQueue (like adding/removing items), but the PlayQueue support in `python-plexapi` seems to be incomplete unfortunately.

**Comment by maykar** [comment]
Ah, right. Yeah, I saw the open PlexAPI issue mentioning that you can't add to playQueue at the moment as well. I should look into just accessing Plex's API directly for things like this. The reason I'm trying to pass arrays is that I need to filter show, season, etc with the user options like "unwatched".

**Comment by maykar** [comment]
Looks like the best option is going to be waiting for your PR as well as waiting on a [PR to Pychromecast](https://github.com/home-assistant-libs/pychromecast/pull/404/files) as currently it doesn't accept playlists. So while your PR to Python-PlexAPI will work great on Plex Clients, Chromecasts will have to wait for the other PR for similar results.

**Comment by maykar** [comment]
Few updates on this. @jjlawren is doing some great things with Python-PlexAPI to add features and methods to playqueues and once his PR is pulled I have a PR of my own for Pychromecast that fixes playing of playlists and adds the ability to play playqueues. These things will allow for much greater flexibility with continued playback of filtered playqueues like "unwatched" and others.

I've also recently discovered a way to have continued playback for items not using filters, like whole shows or whole seasons. I may release this before the above changes are implimented.

**Comment by maykar** [comment]
Pushed a minor release before this feature, still need to finish up some features with this one for next release.

**Comment by maykar** [comment]
Added in 1.0.0. Please check out the [update guide](https://github.com/maykar/plex_assistant/blob/master/ver_one_update.md)
