### ISSUE TITLE
Is Home Assistant a key requirement

### ISSUE THREAD

**Issue by Paul-Reed** [maykar/plex_assistant#37]
Hi, more a question than an issue, but is HA a key requirement for this to work?
As a node-RED user, I have no purpose for using HA, but would really like to add Google Home functionality to Plex.
Another reason for not wanting to use HA is that I have a low performance server, and don't want to dilute Plex performance.

**Comment by maykar** [comment]
This project requires HA, but once things are more fleshed out I may expand this into another stand alone project.

**Comment by Paul-Reed** [comment]
Ok. Thanks for a quick reply.
