### ISSUE TITLE
Use Google Assistant's Default TV before default_cast

### ISSUE THREAD

**Issue by kylezimmerman** [maykar/plex_assistant#39]
Want to start off by saying how awesome this project is! I could never get Phlex or FlexTV to work, but I got this up and running very quickly, and it just works. Thank you!

One thing I noticed during setup, is that while there is the `default_cast` option, it only allows a single value. 

In the Google Home settings, you are able to set a "Default TV" per Google Home device. I'm not sure if it's possible to access that default value, but if it is, it would be awesome if that value could be used if a device is not explicitly mentioned, before falling back to `default_cast`. This is the way that other services work (e.g. Netflix, Spotify, etc.).

Ideally:

- **If I'm in the living room**, the living room Google Home would hear me say "Ask plex to play Futurama" and it would play on the **living room TV**.
- **If I'm in the bedroom**, the bedroom Google Home would hear me say "Ask plex to play Futurama", and it would play on the **bedroom TV**.
- **If I ask my phone** "Ask plex to play Futurama", it wouldn't know where to play it, so it would fall back to playing it on `default_cast`.
- And finally, if I explicitly say "Ask plex to play Futurama on the living room TV", it would play on the living room TV.

**Comment by maykar** [comment]
Unfortunately, that information isn't provided when the command is sent. I agree that this would make things much easier and if there is a way to do this in the future I'll be sure to add it.
