### ISSUE TITLE
Any chance to implement DVR?

### ISSUE THREAD

**Issue by barisahmet** [maykar/plex_assistant#4]
Is that possible to implement "Live TV & DVR" channels as well?

**Comment by maykar** [comment]
This project uses [python-plexapi](https://github.com/pkkid/python-plexapi) and, unfortunately, those options aren't implimented. If at any point it adds those features I could look into it. They have a [feature request](https://github.com/pkkid/python-plexapi/issues/182) for this on the project and I've subscribed to be notified of changes.
