### ISSUE TITLE
Kodi addon as device

### ISSUE THREAD

**Issue by formatBCE** [maykar/plex_assistant#40]
Although Kodi Plex addon is shoown in Hassio as device, with media_player entity, Assistant sensor does not see it - and can't play on it.
I tried 'tell plex to update sensor', reboot Hassio and put "Plex for Kodi" as default cast.
Is it possible, or not? And if so, how to achieve this?
Thank you!!!

P.S. sensor does see my GHome mini and can play (sound of) movies and shows to it.

**Comment by maykar** [comment]
I don't use Kodi myself, but can you try opening the Plex app in Kodi and then updating the sensor to see if it shows as a Client in the sensor. Sometimes Plex takes a minute to recognize clients as being open.

**Comment by formatBCE** [comment]
Hello.
I tried it many times (i'm engineer, so i'm repeating steps several times
in case of troubles).
Hassio is seeing Kodi itself, and Kodi's instance of Plex client. Sensor
does not, even after several updates and full restart.

If i can help testing it, please let me know.

**Comment by maykar** [comment]
Does Plex recognize it as a client? You can check by going here `PLEX-IP-AND-PORT/clients?X-Plex-Token=YOUR-PLEX-TOKEN` while it is open in Kodi (again, it could take a minute to appear).

If Plex doesn't see it as a client then this will probably have to wait for a feature I'm working on to include HA media players as devices.

**Comment by formatBCE** [comment]
Hmmm, it's not listed there.
In that XML i see just local Plex related items (127.0.0.1, 169.254.. and
local Plex ip).

Ok, looks like i won't be able to do it :(
Thank you for helping me out!

**Comment by maykar** [comment]
Going to close this one for now, but when this is possible either through an HA update or an update to one of the libraries this uses it will be added. I'll be sure to comment here to let you know.

**Comment by formatBCE** [comment]
Thank you for the update. Will be waiting. ;)
