### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by legolas0802** [maykar/plex_assistant#47]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:82
First occurred: 12:17:42 (1 occurrences)
Last logged: 12:17:42

Detected integration that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report issue to the custom component author for plex_assistant using this method at custom_components/plex_assistant/__init__.py, line 78: get_chromecasts(blocking=False, callback=cc_callback)

**Comment by maykar** [comment]
Thank you for bringing this to my attention. Good looking out on the HA team for this warning, informative and gets the info out to where it's needed. Will push a fix for this later today.

**Comment by maykar** [comment]
Added in 0.2.6

**Comment by legolas0802** [comment]
Thanks man

Mauro Cimino

Il dom 20 set 2020, 18:49 Ryan Meek <notifications@github.com> ha scritto:

**Comment by legolas0802** [comment]
excuse the disturbance again, same problem:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:82
First occurred: 20:34:22 (1 occurrences)
Last logged: 20:34:22

Detected integration that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report issue to the custom component author for plex_assistant using this method at custom_components/plex_assistant/__init__.py, line 89: get_chromecasts(blocking=False, callback=cc_callback,

**Comment by maykar** [comment]
Will look into it further and reopen, thanks.

**Comment by maykar** [comment]
Is this still an issue for you in the latest release?

**Comment by legolas0802** [comment]
I have not seen the error since, thanks
