### ISSUE TITLE
Unwatched show not found 

### ISSUE THREAD

**Issue by Pegasystem** [maykar/plex_assistant#48]
The unwatched command does not seem to work for some reason. Whenever I say "tell Plex to play unwatched Breaking Bad" or "tell Plex to play the next Breaking Bad", it'll reply with "unwatched Breaking Bad not found". It does correctly translate "play the next" or "play next" to "unwatched", but then it doesn't find any unwatched episodes. Other requests work fine, e.g. if I leave out the unwatched, it'll play the first episode of the first season (although I must admit I expected the default behaviour to be to continue where I left off, but that's another issue and probably personal preference).

My Plex is synced with Trakt and On Deck shows several in-progress shows with the next episode correctly, including Breaking Bad used here as an example.

**Comment by maykar** [comment]
Did a bit of testing and it does seem there is a bug with the "unwatched" keyword, will look into it. Currently working on a major rewrite of this component.

However, playing the first unwatched episode of a show is the default behavior. So just saying "tell Plex to play Breaking Bad" should play the first episode marked as unwatched in plex. Have just tested this as well and it's working as it should. Let me know if that is working for you.

**Comment by demonspork** [comment]
A note on this topic: is it possible to check for "on deck" episodes of a series and allow that to preempt unwatched?
For example:
I was watching The Good Place on Netflix, but it ended on season 3.
I had all 4 seasons on Plex, but unwatched.
I started playing the good place on season 4 episode 1 leaving seasons 1,2,3 all unwatched. 
The on deck episode was season 4 episode 2, but Plex assistant played season 1 episode 1.

**Comment by maykar** [comment]
Give the latest release a try 0.2.9

Should fix unwatched issues as well as some other options.

@demonspork 
I'd rather not change the behavior of unwatched for something like that. That should be handled by either marking those seasons as watched in Plex or by using commands like `"Play The Good Place onDeck "`, `"Play unwatched season 4 of The Good Place"`, etc.

The onDeck filtered by show was broken before, so thanks for the question. It's now fixed in 0.2.9

**Comment by maykar** [comment]
Just to add a bit more to this, once some PRs 🤞 get pulled to HA, then things like continuous playing from single episodes and other exciting features will be added which would help in situations like these.

**Comment by maykar** [comment]
Is the original issue still a problem in the latest release?

**Comment by maykar** [comment]
Going to close this one as the original issue has, I believe, been solved as well as a handful of others that were found while investigating. So, thank you both. If this is still an issue, please let me know.
