### ISSUE TITLE
Play next episode of

### ISSUE THREAD

**Issue by fillwe** [maykar/plex_assistant#5]
Hello! Just wanna start by saying that the integration works great, fantastic work! I never got Phlex working right either and I really think this is so much nicer implemented as well! 

It might just be me but I think it would be nice to be able to say “play next episode of (tv show)” and it would play the next unwatched episode of that series.

I get that the phrasing could be an issue but this is the most natural way I would do it when we are just sitting down and want to play the next episode of a specific series we are watching. I know there are alternative phrases for this already implemented but to me they don’t feel as natural.

**Comment by maykar** [comment]
I like it, make's sense. It is more natural than saying "play unwatched (tv show)". I'll see what I can do.

**Comment by maykar** [comment]
Added in 0.0.4
