### ISSUE TITLE
Plans for Music support?

### ISSUE THREAD

**Issue by jasii** [maykar/plex_assistant#50]
Loving plex assistant so far. I see music and audio isn't supported at the moment. Any plans to add it in the future?

**Comment by maykar** [comment]
Music support is in the works, but I unfortunately couldn't give any ETA.

**Comment by murraykessell** [comment]
Yes it's great. Music and Playlist support would be an added bonus

**Comment by jasii** [comment]
@murraykessell 
In .117 Plex support for chromecast was added. You can do this now. It's not voice controlled awesomeness like plex assistant, but you can still do some awesome stuff!

example https://www.home-assistant.io/integrations/plex/#service-play_media

entity_id: media_player.living_room_speaker
media_content_type: PLAYLIST
media_content_id: 'plex://{ "playlist_name": "Playlist name", "shuffle": "1" }'

**Comment by Ameglialuna** [comment]
Any news about music support? It would be a great feature!

**Comment by maykar** [comment]
https://github.com/maykar/plex_assistant/issues/50#issuecomment-701064743

**Comment by UndarkAido** [comment]
The thing that's bummed me the most about switching from Google Play Music to Plex has been the easy casting. Looking forward to this, and thank you for what you've done so far!

**Comment by mcs1998** [comment]
I have added a version with music support in  a fork. mcs1988.
Seems to work ok

**Comment by maykar** [comment]
If you have managed to add music support I would suggest adding a pull request, but it looks like your branch is currently missing commits?

Looking at the changes your branch currently has, it adds music related words to localize.py without adding logic to handle those new commands, changes the name of a function without actually updating the function (that function only searches shows and movies ATM and changing it's name without updating it in helpers.py would cause it to fail), and adds proxyThroughServer (which should be configurable as it causes problems on some setups). Did you update helpers.py and it's just not reflected on your fork, specifically the `video_selection/media_selection` function?

**Comment by yeahme49** [comment]
> I have added a version with music support in a fork. mcs1988.
> Seems to work ok

I would love to try your version but when trying to load the custom component in HA I get an error ImportError: cannot import name 'media_selection' from 'custom_components.plex_assistant.helpers' (/config/custom_components/plex_assistant/helpers.py)

Can you confirm that whats in your repo is up to date with all your changes?

**Comment by mcs1998** [comment]
Hi,
I will check today.
Cheers
Michael

**Comment by oysteinkrog** [comment]
@mcs1998 Any news? I would love to try your changes

**Comment by mcs1998** [comment]
Hi,
I am drowning in stuff itm but will have a look soon.
Sorry about the delay.
cheers
Michael

**Comment by NovaViper** [comment]
> I have added a version with music support in a fork. mcs1988.
> Seems to work ok

How do I go about setting up your version?

**Comment by maykar** [comment]
See my [previous comment](https://github.com/maykar/plex_assistant/issues/50#issuecomment-756111771).

Currently his fork will not work, in it's current state all it does is add in some music related keywords to the translations and changes the name of a function without actually updating the functions name when it's defined. So, not only does it not have the ability to play music it will fail to function all together.

Since his fork was made version 1.0.0 came out. 1.0.0 adds, among other things, the ability to play media items continuously. So now you could actually listen to full playlists and albums rather than a single song. Music support is next on my list and there are other people interested in helping make that happen.

I would advise patience and if mcs1988 actually has something to contribute, I look forward to seeing it implemented in the new version of Plex Assistant.

**Comment by NovaViper** [comment]
Ah ok

> See my [previous comment](https://github.com/maykar/plex_assistant/issues/50#issuecomment-756111771).
> 
> Currently his fork will not work, in it's present state all it does is add in some music related keywords to the translations (with no logic to handle those keywords) and changes the name of a function without actually updating the functions name when it's defined or what it does (which is only search movies and shows). So, not only does it not have the ability to play music, it will fail to function all together.
> 
> After his fork was made version 1.0.0 came out. 1.0.0 adds, among other things, the ability to play media items continuously. This provides the ability to play full playlists and albums rather than a single song when music support is added, this was not possible until 1.0.0. Music support is the next big feature on my list and there are other people interested in helping make that happen.
> 
> I would advise patience and if mcs1988 actually has something to contribute, I look forward to seeing it implemented in the new version of Plex Assistant.

Ah ok, thanks for the heads up!

**Comment by maykar** [comment]
Music support added in [1.1.0](https://github.com/maykar/plex_assistant/releases/tag/1.1.0)

Big thanks to @yeahme49 for their help implementing music support, testing, and initiating the push to get this started, it's very much appreciated.

**Comment by NovaViper** [comment]
Heck yeah! Glad to see this got added! Im gonna give it a spin tonight :D
