### ISSUE TITLE
Only Call Service works for me and Google Assistant doesn't send the command

### ISSUE THREAD

**Issue by bundy911** [maykar/plex_assistant#51]
I can run Plex Assistant commands through call service perfectly, however Google Assistant won't process my command. It will say "Ok, performing action" but doesn't actually cast to my Chromecast.

**Comment by maykar** [comment]
What service did you set up for triggering Google Assistant: IFTTT or DialogFlow? Did you add the required automation or intent script? Do you get any errors in your log?

**Comment by bundy911** [comment]
I used IFTTT.
I basically copied and pasted all code from the installation page.

I have excluded my URL and Token from the screenshots but here is what I put in my config. Not sure where I went wrong in the steps.

It seems Google can understand what I mean but doesn't process my request like how the call service function does.

![image](https://user-images.githubusercontent.com/72123704/94736188-2a5f9780-03af-11eb-9387-04abc79ec1e1.jpeg)

![image](https://user-images.githubusercontent.com/72123704/94736249-46fbcf80-03af-11eb-9f9c-4e372e66fb80.jpeg)

**Comment by maykar** [comment]
Ah okay, so this seems to just be a config issue. You're defining `automation:` twice and are using an import for your automations.

So, instead of having this in your configuration.yaml file```
automation:
  - alias: Plex Assistant Automation
    trigger:
    - event_data:
        action: call_service
      event_type: ifttt_webhook_received
      platform: event
    condition:
      condition: template
      value_template: "{{ trigger.event.data.service == 'plex_assistant.command' }}"
    action:
    - data_template:
        command: "{{ trigger.event.data.command }}"
      service_template: '{{ trigger.event.data.service }}'
```

You would instead have something like this in your automations.yaml file:

```
- alias: Plex Assistant Automation
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition:
    condition: template
    value_template: "{{ trigger.event.data.service == 'plex_assistant.command' }}"
  action:
  - data_template:
      command: "{{ trigger.event.data.command }}"
    service_template: '{{ trigger.event.data.service }}'
```

**Comment by maykar** [comment]
If you don't have a automations.yaml file, just delete this line `automation: !include automations.yaml`

**Comment by bundy911** [comment]
Great so it now appears in my list of Automations, however upon restarting I get the Notification that there was something wrong in the config:

![image](https://user-images.githubusercontent.com/72123704/94742401-fd17e700-03b8-11eb-85be-6b54658ae224.jpeg)

Here's the automations and config yaml's at the moment:

![image](https://user-images.githubusercontent.com/72123704/94742451-0acd6c80-03b9-11eb-8fa4-1379aefbd3d2.jpeg)
![image](https://user-images.githubusercontent.com/72123704/94742465-0f922080-03b9-11eb-9dd3-0b5199f00c2a.jpeg)

Could this be because my Plex server is actually offline at the moment and therefore cannot start properly?

**Comment by maykar** [comment]
Yes, this is most likely because your plex server is offline. You should never post screenshots of code, it makes it near impossible to try and find your issues. Copy and paste your code in a code block. Use three backticks ``` before the first line of code and at the end so that it get's formatted correctly and is easy to read.

**Comment by bundy911** [comment]
Thanks mate I will try it when I can turn on my PC/media server - currently remote accessing and copy+pasting the code is seeming difficult on iPhone :/ sorry for screenshots

**Comment by bundy911** [comment]
All good now! Thanks for your assistance - will buy you a coffee later :)
