### ISSUE TITLE
Can't open a film on chromecast with plex

### ISSUE THREAD

**Issue by Spox03** [maykar/plex_assistant#52]
Hello,

I got trouble making work plex assistant again.
I reinstalled it after migrating from home assistant to hassio and now i have an error in the logs each time i send a command.

I use IFTTT.
i got an Plex software upgrade yesterday, that the first time i try to cast from plex since the upgrade.
The TV start the cast and show the message 'Ready to cast' but nothing start and i have the following error in the logs :

```
Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py:721
First occurred: 23:31:10 (1 occurrences)
Last logged: 23:31:10
[Bbox(192.168.1.3):8009] Exception caught while sending message to controller ReceiverController: Message urn:x-cast:com.google.cast.receiver from receiver-0 to *: {'requestId': 3, 'status': {'applications': [{'appId': '9AC194DC', 'appType': 'WEB', 'displayName': 'Plex', 'iconUrl': 'http://lh3.ggpht.com/F-carnehpMLNP_IxDt3-IhX9qlnPZcgnC1Ri8E9xkkkIWoeWI_GcD5ZeIQlNkKblg2jOvZLHUm-metNK', 'isIdleScreen': False, 'launchedFromCloud': False, 'namespaces': [{'name': 'urn:x-cast:com.google.cast.debugoverlay'}, {'name': 'urn:x-cast:com.google.cast.cac'}, {'name': 'urn:x-cast:plex'}, {'name': 'urn:x-cast:com.google.cast.broadcast'}, {'name': 'urn:x-cast:com.google.cast.media'}], 'sessionId': '37f9f646-a516-46b0-ac51-be5a2793f874', 'statusText': 'Plex', 'transportId': '37f9f646-a516-46b0-ac51-be5a2793f874', 'universalAppId': '9AC194DC'}], 'isActiveInput': True, 'isStandBy': False, 'userEq': {}, 'volume': {'controlType': 'attenuation', 'level': 0.13333334028720856, 'muted': False, 'stepInterval': 0.06666667014360428}}, 'type': 'RECEIVER_STATUS'}

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 707, in _route_message
    handled = self._handlers[message.namespace].receive_message(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1140, in receive_message
    self._process_get_status(data)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py", line 1272, in _process_get_status
    self.app_launch_event_function()
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 449, in app_launched_callback
    self._send_start_play(media, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 406, in _send_start_play
    msg = media_to_chromecast_command(
  File "/usr/local/lib/python3.8/site-packages/pychromecast/controllers/plex.py", line 114, in media_to_chromecast_command
    playQueue = server.createPlayQueue(media, startItem=startItem)
  File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 289, in createPlayQueue
    return PlayQueue.create(self, item, **kwargs)
TypeError: create() got an unexpected keyword argument 'startItem'
```

**Comment by Spox03** [comment]
in automation.yaml
 `- alias: Plex Assistant Automation
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition:
    condition: template
    value_template: '{{ trigger.event.data.service == ''plex_assistant.command'' }}'
  action:
  - data_template:
      command: '{{ trigger.event.data.command }}'
    service_template: '{{ trigger.event.data.service }}'
`

**Comment by maykar** [comment]
How did you install Plex Assistant? And did you install the Dev branch? That's not ready to be used.

Your automation also has a bunch of indentation errors and if that is your actual plex token you need to invalidate it and make a new one, NEVER post stuff like that online.

**Comment by Spox03** [comment]
Hello,

Sorry to alarm you that a plex token i invalidated during my tries.
I installed Plex assistant with Hacs pointing on the Master Branch.

i just rechecked the automation file it is nearly identic to https://github.com/maykar/plex_assistant#in-home-assistant-1
i removed automation since i use an included file.

**Comment by maykar** [comment]
Your Pychromecast version (a library in home assistant) is at a version that is higher than any HA release currently includes. This version will be included in the next version of HA as well as an updated version of another library (PlexAPI). 

The updated version of Pychromecast uses methods that are only included in and rely on the updated version of PlexAPI. What your error is telling me is that Pychromecast has been updated (which it shouldn't be) but PlexAPI has not (which is correct, but causes errors since Pychromecast needs it's updated version now).

The reason I asked about the Dev version of Plex Assistant is that it uses both updated versions of those libraries. I don't know how your hassio install is in this current state, and that is what is confusing me.

The formatting error I am referring to is if you look at the automation code you posted above, everything under `- alias: Plex Assistant Automation` is under indented by one space.

**Comment by maykar** [comment]
Closing as invalid as this isn't an issue with Plex Assistant, but rather an issue with your setup. Feel free to continue the conversation here and I'll try to help in any way I can.

**Comment by maykar** [comment]
You're apparently not the only one. I'm not sure how it's happening but pychromecast is getting updated on peoples systems early, but PlexAPI is not. Going to push an update that should fix the issue.

**Comment by maykar** [comment]
Posted a fix in the new issues post:

https://github.com/maykar/plex_assistant/issues/53#issuecomment-702071654

**Comment by Spox03** [comment]
Hello,

First thing, thank you for your answer and you time, you clearly went above and beyond my expectations

On another topic, I have some kind of gift to find bugs ...
For your answer Hassio tell us about a pending update for home asssitant 0.115.6 in the interface, i guess many people did it in the morning (explaining the multiples case).

Thank you for your answer i was planing to downgrade the library with Pip in the container i guess it is no use now.
Thank you for the fix.

**Comment by maykar** [comment]
Not sure why it got pushed in 0.115.6 and it's not mentioned in the release notes either. I can't imagine mine is the only component that would be affected, but it's possible.

**Comment by maykar** [comment]
Please, let me know if that fixes it for you. If it does I will push an update to be safe.

**Comment by Spox03** [comment]
Hello, 
It work for me with you solution, thank you very much, that a good job,

on another subject, on the contrary, you have the only add-on i am aware of capable of doing chrome-cast on Home assistant (Flex.tv is broken and don't install successfully as a Plex extension),

**Comment by maykar** [comment]
Oh, I was more wondering if any other add-on use's the same Pychromecast methods I do. As they would break as well.

**Comment by maykar** [comment]
Note:

Made edits to my comments in the above conversation to make things a bit more clear. 0.115.4 updated Pychromecast as part of a fix to camera streams. I have since bumped the version of PlexAPI in the 0.3.0 release of Plex Assistant.

**Comment by Spox03** [comment]
> 
> 
> Oh, I was more wondering if any other add-on use's the same Pychromecast methods I do. As they would break as well.

The Bbox android system didn't upgrade so now the Hassio's native chrome cast support is broken for Bbox.
