### ISSUE TITLE
Jump forward/back not working 

### ISSUE THREAD

**Issue by Evil1220** [maykar/plex_assistant#55]
So i have everything setup and working for the most part, the only thing that eludes me is the jump forward or backward command  as whenever i attempt it, my google assistant replies with the standard "sorry something went wrong" and then freezes whatever is running plex into an idle state to which i have to tell google to "stop" before i can run any other commands. I restarted HA then attempted the commands again to get a clean error report, but the only thing showing up is the standard 2 lines.

2020-10-02 11:16:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-02 11:16:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plex_assistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

I checked IFTTT but the applet ran correctly and there's no error logs. Ill try adding in some manual commands to see if that helps but for now this is the issue i ran into.

Full build for this:
**Rasberry Pi 3:** 
    - Running a docker container for HA and having it use my external port forwarded IP so that IFTTT can reach it, as well as using the IFTTT key 
    - Running plex_assistant with all details specified in documentation besides the aliases for the config file
**Google Nest mini 2nd Gen:**
    - My primary google assistant device that i use
**Google chromecast 3rd gen:**
    - Connected to small LG TV that i don't feel like looking up the specific model for unless really needed.

**Comment by maykar** [comment]
Yeah, I've noticed this myself and am working on getting a fix into the next release. The jump commands seem to work fine on Plex clients, but not on Google devices. Thanks for the report!

**Comment by Evil1220** [comment]
Not a problem, also thanks for the insanely quick response. I'm loving how this functions so far, so even with the jump commands issue, i'm fully enjoying it. So thank you!

**Comment by mgrinspan** [comment]
I just set up this integration and the play command works, but pause and stop do not. Sounds like it could be related to this issue, but let me know if it's just me. Thanks 😄

**Comment by fcastilloec** [comment]
I've seen this issue before using plex_assistant. I can pause and resume with my Chromecast, either using the Google Home app, or with voice via Google Assistant (phone or Google Home) but fast forward or rewind has never worked.

The only way I see this working is by not sending the commands via chromecast, but instead "resuming" at a specific time. So if you're watching something, the current time has to be known in order to jump forward.

Also, it would be awesome if we could configure the commands. For example, we're used to saying "forward" or "fast forward" rather than "jump forward", followed by the number of minutes/seconds I wanted to jump.

**Comment by maykar** [comment]
Fixed in 1.0.0. Please check out the [update guide](https://github.com/maykar/plex_assistant/blob/master/ver_one_update.md)
