### ISSUE TITLE
Playing movies from another library

### ISSUE THREAD

**Issue by fillwe** [maykar/plex_assistant#6]
Noticed a small issue that I would like to check if it is possible to fix. 

Since my kids are watching plex quiet a lot I have created a separate “children’s movie” library. It seems movies that I ask for are only able to parse my main movie library. Would it be possible for a fix to this or would it be too complicated to solve? Worst case scenario I will put back everything into one folder!

**Comment by maykar** [comment]
I'll see what I can do about custom libraries, thanks!

**Comment by rossssco** [comment]
I would also very much like this feature. 
I had HDD fail and am currently relying on a friends shared library.
None of these objects are scanned/available to plex_assistant?

**Comment by maykar** [comment]
Added in 0.0.4
