### ISSUE TITLE
Plex Managed User Support

### ISSUE THREAD

**Issue by zhdenny** [maykar/plex_assistant#60]
I know you already addressed adding multiple Plex Account support.
https://github.com/maykar/plex_assistant/issues/17

But.....what about Plex Managed User Suppport? All my users are under One single Plex account (my account). Plex supports multiple "managed users" in a single account. Can/Will plex_assistant support managed users?

**Comment by maykar** [comment]
I don't see a practical way to do this. Unless each user always announces their username with every command or has their own trigger words, there is no way to distinguish between users. This is just info that isn't passed along with IFTTT, maybe it's possible with DialogFlow, but I'll have to do some research into it.

**Comment by maykar** [comment]
Since this has no practical solution at the moment, I'm closing, but if at some point there is a good way to implement this I will revisit.

**Comment by zhdenny** [comment]
I've always been able to see everything playing and what Managed User is playing it from parsing out of this URL

`https://plex_url:port/status/sessions?X-Plex-Token=token_goes_here`
or if you reverse proxy
`https://plex.domain.com/status/sessions?X-Plex-Token=token_goes_here`

**Comment by maykar** [comment]
Doesn't really help since that info only exists after something is already playing.

There is no current way to detect who initiated the Plex Assistant command. IFTTT doesn't provide info about what user is speaking or even what device is being spoken to, it may be possible with DialogFlow, but that will further complicate the already messy DialogFlow setup if it is even a possibility.

**Comment by zhdenny** [comment]
Ah Ok, I understand.....So aside from the issue about receiving the command (what to play on what device and managed user).....what is the command to send to plex (granted you knew what to play, where, and on which manager user)?

Maybe you could just point me to some documentation :)

**Comment by zhdenny** [comment]
Nevermind, I think I can piece together my own thing using this:
https://www.home-assistant.io/integrations/plex/

**Comment by maykar** [comment]
Some things to check out would be the two libraries that this uses [Python-PlexAPI](https://python-plexapi.readthedocs.io/en/latest/) for talking to plex and [Pychromecast](https://github.com/home-assistant-libs/pychromecast) for casting to Google Cast devices and Plex Clients.

The built in plex integration doesn't have any kind of user support built in and right now I believe can only cast to Plex Clients.

**Comment by maykar** [comment]
It's important to note that as far as Plex Assistant is concerned, none of the above documentation is going to solve your issue. You would need IFTTT to add features to support this or find a way to modify the DialogFlow integration to include device/user information.
