### ISSUE TITLE
Can't play from plex yet

### ISSUE THREAD

**Issue by Kurtroosbeek2** [maykar/plex_assistant#69]
I followed all the steps, but Google Assistant - connected with Home Assistant - keeps replying 'sorry I can't play from plex yet'.

**Comment by WesNz** [comment]
i get the same issue...u manage to fix this?

**Comment by Kurtroosbeek2** [comment]
> i get the same issue...u manage to fix this?

Nope - no responses - no solution.

**Comment by maykar** [comment]
@WesNz I replied to your issue.

@Kurtroosbeek2  How did you set it up, with IFTTT or DialogFlow? Do you get any errors in your logs? Using the same info are you able to get the default HA Plex Integration setup?

**Comment by spicerackk** [comment]
I am also having this issue, I set it up via IFTTT. I am also unable to see the component service to test it.

**Comment by XoniBlue** [comment]
Im getting the same issue, Im about to add the debug params in to see what i get, but off the bat im not getting the sensor to detect devices. the automations shows up but no "companion sensor"

**Comment by maykar** [comment]
Check out the [troubleshooting guide](https://github.com/maykar/plex_assistant/blob/master/troubleshooting.md) and provide as much info from there as you can.

Also, just updated the readme since IFTTT's interface has changed.
