### ISSUE TITLE
IFTTT Applet Failed Timeout Error

### ISSUE THREAD

**Issue by mawcuzz** [maykar/plex_assistant#72]
I followed the guide to a T! Got to the point where I wanted to test it to work. The sensor found all devices chromecasts as well. Then this error message popped up on IFTTT.

I even tried Dialogflow and I couldn't find any errors from that effort, though it still didn't work.

**Comment by mawcuzz** [comment]
![Screenshot from 2020-12-15 09-27-00](https://user-images.githubusercontent.com/41217153/102253475-36da9300-3ebc-11eb-8e5a-5763b8916454.png)

**Comment by maykar** [comment]
Is there anything that would be preventing IFTTT from connecting to your HA instance? Is your HA instance accessable from outside your network (using Nabu Casa, duckdns, etc.)?
