### ISSUE TITLE
Can't assign 'Plex' for Implicit Invocation in Google Assistant Integration Settings

### ISSUE THREAD

**Issue by colinmcintosh** [maykar/plex_assistant#73]
Hi, I followed the instructions for setting up Plex Assistant using DialogFlow and I'm able to complete all of the steps specified except for assigning 'Plex' to the Implicit Invocation field in DialogFlow Google Assistant Integration Settings. 'Plex' doesn't appear as one of the valid options and typing 'Plex' will cause the value to not be saved when the modal is closed. Here's an image of the list of available intents:

![image](https://user-images.githubusercontent.com/4840146/103842729-660f9a80-504b-11eb-9245-1b3c598e644a.png)

As a result it seems like the only option I have for interacting with Plex is to use the `Talk to Plex` then saying "Play blah on blah". I can't get the intent to run by issuing the command "Tell Plex to play blah on blah". Here's an example from the Google Actions console:

![image](https://user-images.githubusercontent.com/4840146/103843064-fd74ed80-504b-11eb-94b5-5f93a22f3e2d.png)

Any advice on how to enable this intent for Implicit Invocation?

**Comment by maykar** [comment]
This is a duplicate issue of #66, they were able to get it to work [after trying multiple times](https://github.com/maykar/plex_assistant/issues/66#issuecomment-723464449). All I can say is that the instructions work and that dialogFlow is finicky.
