### ISSUE TITLE
Sorry i cant do that yet

### ISSUE THREAD

**Issue by WesNz** [maykar/plex_assistant#77]
Cant seem to cast or even get google to understand the plex command. I followed the tutorial for "Homeassistant conversation setup"

Ok google, tell plex to play friends
Google : Sorry i cant do that yet.

in my main logs i see : 
`Logger: homeassistant.bootstrap
Source: bootstrap.py:394
First occurred: 8:22:56 PM (3 occurrences)
Last logged: 8:24:56 PM
Waiting on integrations to complete setup: plex_assistant`

**Comment by maykar** [comment]
If you followed only the Home Assistant Conversation setup then it will only work with the HA conversation integration (the built in voice assistant). If you want to use it with Google Assistant you need to setup one of the [Google Assistant Triggers](https://github.com/maykar/plex_assistant#google-assistant-triggers) either IFTTT (preferred) or DialogFlow.

**Comment by spicerackk** [comment]
I followed all the instructions, and continue to get a "sorry, I can't play from Plex yet". I set it up with IFTTT, no errors in logs, and I also can't see the service as it apparently doesn't exist, even though I have installed it through HACS.
