### ISSUE TITLE
Waiting on integrations to complete setup: plex_assistant

### ISSUE THREAD

**Issue by spicerackk** [maykar/plex_assistant#78]
I am getting a message in Logs saying:

```WARNING (MainThread) [homeassistant.setup] Setup of plex_assistant is taking over 10 seconds. ```
```WARNING {MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: plex_assistant```

It is also generating another warning:

```WARNING (SyncWorker_0) [homeassistant.components.zeroconf.usage] Detected code that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report this issue.```

**Comment by spicerackk** [comment]
Fixed this myself. Just had to be patient.

**Comment by maykar** [comment]
To help others that may have the same issue, would you mind sharing how you resolved the issue?
