### ISSUE TITLE
Feature: Remote Plex users

### ISSUE THREAD

**Issue by spicerackk** [maykar/plex_assistant#79]
Not sure if this is something that can be implemented, or if it's something each user would have to configure their own instance of HA/Plex_Assistant, 

But having remote Plex users utilise voice control also would be a cool feature!

**Comment by maykar** [comment]
They would need their own setup in order to use this

**Comment by demonspork** [comment]
I think that the question that is relevant from this is for people who _don't_ have their own Plex server, but have access to a remote Plex server. I have some family members who have a home-assistant installation but not a plex server, they watch from my plex server via me sharing with their plex account. Would they be able to watch from my remote plex server using their account I share with?

**Comment by maykar** [comment]
@demonspork I'm actually already working on this for the next major release. I'm hoping some upstream changes happen in PlexAPI and HA before I release it, but if it looks like that may be a while off I will release sooner.
