### ISSUE TITLE
Default Quality setting

### ISSUE THREAD

**Issue by Deathbot64** [maykar/plex_assistant#85]
Hey there, Got Plex Assistant working and it is great. But I was hoping that a video quality setting could be added or at least a customizable default setting. I dont have the best internet quality at my home but the server is in a remote place with better internet service so whenever I try to play anything it will play at the best quality which can cause stuttering issues depending on the file. so far to fix this I have limited the remote quality for everyone but I have a lot of users who have better internet then me so a setting like this for plex assistant would be great for me and everyone on my server. 

Thanks for the great work on this!

**Comment by maykar** [comment]
I assume you're talking about casting to Chromecast devices as other Plex clients have the ability to set the quality per device. Unfortunately, there are no methods available to me via HA or the libraries I use to make this happen.
