### ISSUE TITLE
Translations for new 1.0.0 features

### ISSUE THREAD

**Issue by maykar** [maykar/plex_assistant#87]
Tagging all that have done translations:  @exetico @hwikene @Drauboss @KunJakob @ngreis @jokerigno @Guilhem23 @kernehed

Version 1.0.0 added a few new features that required translation: "random", "next", and "previous".

I tried to pick from google translate to the best of my ability for each of the languages. Please take a look below at the translations I used and either reply to this issue with the language and changes that should be made or make a pull request. Also, let me know if the translations used are just fine.

Please, also consider translating `custom_components/plex_assistant/en.json` to a new file with the language code replaced in the file name. Example: `custom_components/plex_assistant/nl.json`.

<details>
  <summary><b>Portuguese</b> :heavy_check_mark:</summary>

* Random: aleatório
* Next: próximo
* Previous: anterior

</details>
<details>
  <summary><b>Italian</b> :heavy_check_mark:</summary>

* Random: casuale
* Next: successivo
* Previous: precedente

</details>
<details>
  <summary><b>Norwegian</b> :heavy_check_mark:</summary>

* Random: tilfeldig
* Next: neste
* Previous: forrige

</details>
<details>
  <summary><b>Danish</b> :heavy_check_mark:</summary>

* Random: tilfældig
* Next: næste
* Previous: forrige

</details>
<details>
  <summary><b>German</b> :heavy_check_mark:</summary>

* Random: zufällige, zufälliges, zufälligen
* Next: nächstes, nächste, nächsten
* Previous: vorheriges, vorherige, vorherigen

</details>
<details>
  <summary><b>Dutch</b></summary>

* Random: willekeurige
* Next: volgende
* Previous: vorig

</details>
<details>
  <summary><b>French</b></summary>

* Random: aléatoire
* Next: suivante
* Previous: précédente

</details>
<details>
  <summary><b>Swedish</b></summary>

* Random: slumpmässigt
* Next: nästa
* Previous: föregående

</details>

**Comment by hwikene** [comment]
Hi. The norwegia translation is ok 👍

**Comment by ngreis** [comment]
Hello

 

Portuguese is ok! 😉

 

Best regards

Nuno Reis

 

De: Ryan Meek <notifications@github.com> 
Enviada: 11 de fevereiro de 2021 17:00
Para: maykar/plex_assistant <plex_assistant@noreply.github.com>
Cc: ngreis <ngreis@sapo.pt>; Mention <mention@noreply.github.com>
Assunto: [maykar/plex_assistant] Translations for new 1.0.0 features (#87)

 

Tagging all that have done translations: @exetico <https://github.com/exetico>  @hwikene <https://github.com/hwikene>  @Drauboss <https://github.com/Drauboss>  @KunJakob <https://github.com/KunJakob>  @ngreis <https://github.com/ngreis>  @jokerigno <https://github.com/jokerigno>  @Guilhem23 <https://github.com/Guilhem23>  @kernehed <https://github.com/kernehed> 

Version 1.0.0 added a few new features that required translation: "random", "next", and "previous".

I tried to pick from google translate to the best of my ability for each of the languages. Please take a look below at the translations I used and either reply to this issue with the language and changes that should be made or make a pull request. Also, let me know if the translations used are just fine.

Please, also consider translating the README.md file and custom_components/plex_assistant/en.json to a new file with the language code added to the file name. Example: README_NL.md and custom_components/plex_assistant/nl.json.

Dutch 

*	Random: willekeurige
*	Next: volgende
*	Previous: vorig

French 

*	Random: aléatoire
*	Next: suivante
*	Previous: précédente

Norwegian 

*	Random: tilfeldig
*	Next: neste
*	Previous: forrige

Danish 

*	Random: tilfældig
*	Next: næste
*	Previous: forrige

German 

*	Random: zufällige
*	Next: nächstes
*	Previous: vorheriges

Portuguese 

*	Random: aleatório
*	Next: próximo
*	Previous: anterior

Italian 

*	Random: casuale
*	Next: successivo
*	Previous: precedente

Swedish 

*	Random: slumpmässigt
*	Next: nästa
*	Previous: föregående

**Comment by exetico** [comment]
Hi 😊

Danish OK, too! 

Tak 🙏

**Comment by jokerigno** [comment]
Italian is ok 👍

**Comment by ciB89** [comment]
For German it really depends on what you are trying to say:

Nächstes:
Spiele nächste Episode vs spiele nächstes [which nobody would say] vs spiele nächsten Film
(Play next Episode vs play next vs play next movie)
This also applies to "vorheriges"

Same for random:
Spiele etwas Zufälliges vs spiele zufälligen Film vs spiele zufällige Serie/Episode
(Play somehting random vs play random movie vs play random series/episode)

So it really should accept "nächstes, nächste, nächsten, vorheriges, vorherige, vorherigen, zufällige, zufälliges, zufälligen"

**Comment by maykar** [comment]
So, the random keyword in the case would be item dependent like your example above, but the "next" and "previous" are just single commands: `tell plex next` or `tell plex previous`.

I don't see a reason all of them would be accepted, but maybe that context changes things.

**Comment by ciB89** [comment]
I guess the point that I am making that in German it would be weird to just say "nächstes" without having the current medium in mind. No German would say "Nächstes" when watching a TV show, they would say "Nächste".

**Comment by maykar** [comment]
Understood, thank you

**Comment by maykar** [comment]
Added the German variants to be released with the next major release that will add music support.

As a heads up for all translators, every item can now accept lists to accommodate languages where context can change the word used and can be used for any kind of variant in general.

For example, before "random" was limited to one word for the translation:

```
        "random" : "random"
```

But with the added feature, in the English translation I've now added this for the music release:

```
        "random": [
            "random",
            "shuffle",
        ],
```

**Comment by Coldrush** [comment]
Hi @maykar! A Dutchie here. I think I can help you here.

Just like in German, there are a few different options:
- Random: willekeurige, willekeurig
- Next: volgende, volgend
- Previous: vorige

Hope this helps!
