### ISSUE TITLE
Error when setting up plex_assistant

### ISSUE THREAD

**Issue by fcastilloec** [maykar/plex_assistant#88]
I just switched to v1.0.0 and I've followed the guide on how to migrate removing any old configuration.
I'm using IFTTT to trigger plex_assistant. I double-checked that the new guide hasn't changed anything from the old configuration regarding setting up the action in IFTTT (not in HA, which was already taken care of by following the migration guide).
HA's Plex integration is working. I can see when somebody is watching on HA.
The issue is not command-specific, rather starting the component itself.
Follow the error shown on HA (I don't have the conversation integration installed):

```
021-02-11 14:03:07 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry None for plex_assistant
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/plex_assistant/__init__.py", line 96, in async_setup_entry
ifttt_listener = await listeners(hass)
File "/config/custom_components/plex_assistant/helpers.py", line 59, in listeners
await hass.services.async_call("conversation", "process", {"text": "tell plex to initialize_plex_intent"})
File "/usr/src/homeassistant/homeassistant/core.py", line 1405, in async_call
raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service conversation.process
```

The section [conversation setup in the README](https://github.com/maykar/plex_assistant#home-assistant-conversation-setup) seems to imply that it's optional and not required for plex assistant to work. Especially since the old version didn't need this integration.

**Comment by maykar** [comment]
`"seems to imply that it's optional and not required"`

It should be, I'll get a fix in soon

**Comment by maykar** [comment]
Should be good in 1.0.1

**Comment by fcastilloec** [comment]
Thanks! By any chance, do you know how long it takes since published to show in HACS?

**Comment by maykar** [comment]
For an installed item: 
* At startup
* Every 30 mins after startup
* When you manually reload the item

https://hacs.xyz/docs/basic/updates
