### ISSUE TITLE
Plex Assistant error after updating Home Assistant to 0.107.6

### ISSUE THREAD

**Issue by gambith** [maykar/plex_assistant#9]
After updating Home Assistant from 0.107.5 to 0.107.6 the Plex Assistant isn't working anymore.

Output from homeassistant.log

2020-03-24 17:19:13 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package python-Levenshtein==0.12.0: ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_tk6lbo_/python-Levenshtein/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_tk6lbo_/python-Levenshtein/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r5ly49o0
       cwd: /tmp/pip-install-_tk6lbo_/python-Levenshtein/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/Levenshtein
  copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-3.7/Levenshtein
  copying Levenshtein/__init__.py -> build/lib.linux-x86_64-3.7/Levenshtein
  running egg_info
  writing python_Levenshtein.egg-info/PKG-INFO
  writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
  writing entry points to python_Levenshtein.egg-info/entry_points.txt
  writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
  writing requirements to python_Levenshtein.egg-info/requires.txt
  writing top-level names to python_Levenshtein.egg-info/top_level.txt
  reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-3.7/Levenshtein
  copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-3.7/Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/Levenshtein
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-3.7/Levenshtein/_levenshtein.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-Levenshtein
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_tk6lbo_/python-Levenshtein/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_tk6lbo_/python-Levenshtein/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g6peeg32/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/python-Levenshtein
         cwd: /tmp/pip-install-_tk6lbo_/python-Levenshtein/
    Complete output (31 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/Levenshtein
    copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-3.7/Levenshtein
    copying Levenshtein/__init__.py -> build/lib.linux-x86_64-3.7/Levenshtein
    running egg_info
    writing python_Levenshtein.egg-info/PKG-INFO
    writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
    writing entry points to python_Levenshtein.egg-info/entry_points.txt
    writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
    writing requirements to python_Levenshtein.egg-info/requires.txt
    writing top-level names to python_Levenshtein.egg-info/top_level.txt
    reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
    copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-3.7/Levenshtein
    copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-3.7/Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/Levenshtein
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-3.7/Levenshtein/_levenshtein.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_tk6lbo_/python-Levenshtein/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_tk6lbo_/python-Levenshtein/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g6peeg32/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/python-Levenshtein Check the logs for full command output.
2020-03-24 17:19:13 ERROR (MainThread) [homeassistant.setup] Setup failed for plex_assistant: Requirements for plex_assistant not found: ['python-Levenshtein==0.12.0'].

**Comment by maykar** [comment]
Levenshtein isn't really required and I'll have a new update up soon that removes it. For now, if you go into the manifest.json and delete the line `"python-Levenshtein==0.12.0"` you should be fine.

**Comment by gambith** [comment]
Thank you, removing the line "python-Levenshtein==0.12.0" in manifest.json fixes the issue.
