### ISSUE TITLE
Next and Previous not working on chromecast

### ISSUE THREAD

**Issue by yeahme49** [maykar/plex_assistant#95]
When casting to a chromecast device (at least with music), previous and next do nothing.

When I was adding music support to the old version, I had added previous and next commands that worked while casting to a chromecast device. I called plex_c.next() (which called https://github.com/home-assistant-libs/pychromecast/blob/master/pychromecast/controllers/plex.py#L283 and I assume that sent the next command right to plex). With the new version by casting to the home assistant media device, it uses the generic chromecast controller and next_track actually calls queue_next (https://github.com/home-assistant-libs/pychromecast/blob/master/pychromecast/controllers/media.py#L440). Since plex doesn't create a queue on the chromecast it doesn't work.

Is it possible to send a queue to the chromecast so the commands would work (I think this is how some apps do it, I'm not too familiar with the actually casting process)? Or to call the PlexController next() while using the home assistant media players?

**Comment by maykar** [comment]
See the issue, the chromecast is playing the playqueue just fine (if you play the whole item it continues to the next as it should), but the media_player entity's next command won't work for this. Would need to initiate the next and previous commands from Plex, looking into it.

**Comment by yeahme49** [comment]
I did just test something that would work but I don't like it as much as calling the commands from plex. If you jump forward 99999 seconds (or anything longer than the file i just tried 99999 since its longer than anything should be including movies) it will go to the next track. That would be a possibility if can't call the commands through plex

**Comment by maykar** [comment]
All else fails, that would be an option. Testing some other solutions now

**Comment by maykar** [comment]
Added Pychomecast just for this, working well. Want to wait for some replies/fixes for open issues before a release.

**Comment by maykar** [comment]
Now in version 1.0.3
